# -*- coding: utf-8 -*-
"""EMBEDDINGS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Le5Ur_qQ-bKz1qkVqBNcm7F-BPU3en9L

#Librerias
"""

import tensorflow as tf
import tensorflow_hub as hub
import numpy as np
import csv

"""#Modelo"""

# 1. Cargar el modelo desde TFHub
print("🚀 Cargando YAMNet...")
model = hub.load('https://tfhub.dev/google/yamnet/1')

# 2. Extraer los nombres de las clases (etiquetas)
class_map_path = model.class_map_path().numpy()
with tf.io.gfile.GFile(class_map_path) as f:
    reader = csv.DictReader(f)
    class_names = [row['display_name'] for row in reader]

print(f"Modelo listo. Se reconocen {len(class_names)} clases de sonido.")

"""#Patrones"""

print("Buscando la matriz de patrones (1024, 521) mediante inspección de firmas...")

weights_matrix = None

# Intentamos extraer las variables de la firma predeterminada del modelo
try:
    # Accedemos a las variables concretas que el modelo usa para "llamar" a la función
    v_list = model.signatures['serving_default'].variables

    for v in v_list:
        if v.shape == (1024, 521):
            weights_matrix = v.numpy()
            print(f"¡Matriz encontrada! Nombre: {v.name}")
            break
except Exception as e:
    print(f"Intento falló: {e}")

if weights_matrix is None:
    print("❌ No se pudo extraer la matriz. El modelo tiene una estructura protegida.")
else:
    print(f"Intento exitoso: Matriz de {weights_matrix.shape[0]}x{weights_matrix.shape[1]} lista.")

# 1. Tu lista oficial de IDs (26 activadores/inhibidores)
ids_activadores = [
    6, 7, 9, 11, 19, 22, 33, 39, 382, 390, 391, 393, 394,
    420, 421, 422, 423, 424, 430, 435, 437, 460, 461, 462, 464
]

# 2. Diccionario para guardar los patrones finales
patrones_safevoice = {}

print("Extrayendo patrones específicos...")

for idx in ids_activadores:
    # Obtenemos el nombre de la clase usando el ID
    nombre = class_names[idx]

    # Extraemos la columna 'idx' de la matriz de pesos
    # Cada columna es un vector de 1024 que representa el "sonido ideal"
    vector_patron = weights_matrix[:, idx]

    # Guardamos en nuestro diccionario
    patrones_safevoice[nombre] = vector_patron

print(f"Se han filtrado {len(patrones_safevoice)} patrones.")
print(f"Primeros 3 activadores listos: {list(patrones_safevoice.keys())[:3]}")

import pickle

# Guardamos como archivo de NumPy para uso en Python/Colab
np.save('patrones_safevoice_26.npy', patrones_safevoice)

# También lo guardaremos como un archivo Pickle, que a veces es más fácil
# de leer si mantienes la estructura de diccionario
with open('patrones_safevoice_26.pkl', 'wb') as f:
    pickle.dump(patrones_safevoice, f)

print("ARCHIVOS GENERADOS:")
print("- patrones_safevoice_26.npy")
print("- patrones_safevoice_26.pkl")

matriz = np.array(list(patrones_safevoice.values()))

print(f"Dimensiones : {matriz.shape}")

"""#Comprobación"""

import numpy as np

# 1. Cargar el archivo que acabamos de guardar
data = np.load('patrones_safevoice_26.npy', allow_pickle=True).item()

print(f"Archivo: patrones_safevoice_26.npy")
print(f"Total de clases extraídas: {len(data)}")
print("-" * 50)

# 2. Listar todas las clases y una pequeña muestra de su vector
for i, (nombre, vector) in enumerate(data.items()):
    # Mostramos los primeros 5 números del vector de 1024
    muestra_vector = vector[:5]
    print(f"[{i+1:02}] Clase: {nombre:<20} | Muestra ADN: {muestra_vector}")

    # Verificación de integridad
    if len(vector) != 1024:
        print(f" ERROR: ¡El vector de {nombre} no tiene 1024 dimensiones!")

print("-" * 50)

"""#Json"""

import json
from google.colab import files # Librería para interactuar con tu explorador local

# 1. Convertimos los vectores de NumPy a listas de Python (necesario para JSON)
patrones_json = {nombre: vector.tolist() for nombre, vector in patrones_safevoice.items()}

# 2. Guardamos el archivo temporalmente en el servidor de Colab
archivo_json = 'patrones_safevoice_26.json'
with open(archivo_json, 'w') as f:
    json.dump(patrones_json, f, indent=4) # 'indent=4' para que el JSON sea legible si lo abres

print(f"Archivo '{archivo_json}' preparado .")

files.download(archivo_json)

"""#pRUEBA"""

import tensorflow as tf
model = hub.load('https://tfhub.dev/google/yamnet/1')
# 1. PREPARACIÓN DEL CONVERTIDOR
# Usamos el modelo que ya tienes en memoria ('model')
# Le decimos que la entrada es un audio (forma indefinida [None] para que acepte cualquier duración)
run_model = tf.function(lambda x: model(x))
concrete_func = run_model.get_concrete_function(tf.TensorSpec([None], tf.float32))

converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])

# 2. OPTIMIZACIÓN (Opcional pero recomendado para móviles de baja gama)
# Esto reduce el tamaño del archivo a casi la cuarta parte (de ~15MB a ~4MB)
converter.optimizations = [tf.lite.Optimize.DEFAULT]

# 3. CONVERSIÓN
tflite_model = converter.convert()

# 4. GUARDAR EL ARCHIVO FINAL
with open('yamnet_safevoice.tflite', 'wb') as f:
    f.write(tflite_model)

print("rchivo 'yamnet_safevoice.tflite' generado.")

import os
import tensorflow as tf

# 1. Análisis de Peso y Almacenamiento
file_path = 'yamnet_safevoice.tflite'
file_size_kb = os.path.getsize(file_path) / 1024
file_size_mb = file_size_kb / 1024

print(f"INFORME DE ALMACENAMIENTO")
print(f"--------------------------------------------------")
print(f"Nombre del archivo: {file_path}")
print(f"Peso del modelo: {file_size_mb:.2f} MB ({file_size_kb:.2f} KB)")
print(f"Nota: Un modelo de < 5MB es ideal para dispositivos de gama baja.")
print(f"--------------------------------------------------\n")

# 2. Análisis de Arquitectura e Interfaz (Tensores)
interpreter = tf.lite.Interpreter(model_path=file_path)
interpreter.allocate_tensors()

input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

print(f"ARQUITECTURA DE ENTRADA/SALIDA")
print(f"--------------------------------------------------")
# Entrada
print(f"ENTRADA (Micrófono):")
print(f"   - Índice: {input_details[0]['index']}")
print(f"   - Forma (Shape): {input_details[0]['shape']}")
print(f"   - Tipo de dato: {input_details[0]['dtype']}")
print(f"   - Cuantización: {input_details[0]['quantization']}")

print(f"\nSALIDAS (Procesamiento):")
for i, output in enumerate(output_details):
    nombre_salida = "Scores (Clasificación)" if i == 0 else "Embeddings (ADN Sonoro)" if i == 1 else "Spectrogram"
    print(f"   Salida [{i}] - {nombre_salida}:")
    print(f"      - Índice: {output['index']}")
    print(f"      - Forma Final: {output['shape']}")
    print(f"      - Tipo de dato: {output['dtype']}")

print(f"--------------------------------------------------")

# Cargar el nuevo intérprete
interpreter = tf.lite.Interpreter(model_path="yamnet_safevoice.tflite")
interpreter.allocate_tensors()

output_details = interpreter.get_output_details()
print(f"La salida de Embeddings está en el índice 1 y tiene forma: {output_details[1]['shape']}")

"""#audio"""

from google.colab import files
import os

# 1. Solicitar la subida del archivo
uploaded = files.upload()

# 2. Obtener el nombre del archivo subido
for filename in uploaded.keys():
    audio_path = os.path.join(os.getcwd(), filename)
    print(f'\n Archivo subido con éxito: {audio_path}')

# Guardamos la ruta en una variable para el siguiente paso (preprocesamiento)
print(f"La ruta de tu audio es: {audio_path}")

from IPython.display import Audio, display

# 1. Verificar si el archivo existe antes de intentar reproducirlo
if os.path.exists(audio_path):
    print(f"Reproduciendo: {filename}")

    # 2. Crear el reproductor de audio
    # autoplay=False para que no empiece a sonar de golpe al ejecutar la celda
    display(Audio(audio_path, autoplay=False))
else:
    print("Error: No se encontró el archivo de audio.")

"""#RMS"""

import matplotlib.pyplot as plt
import librosa
# --- 2. DEFINICIÓN DEL GATILLO (TRIGGER) RMS ---

def pipeline_safevoice_completo(path, sensibilidad=0.3):
    # Cargar audio a 16kHz (Frecuencia que requiere YAMNet)
    y, sr = librosa.load(path, sr=16000, mono=True)

    # Calcular energía RMS (Root Mean Square)
    # El hop_length 512 da una buena resolución temporal
    rms = librosa.feature.rms(y=y, hop_length=512)[0]

    # Normalizar de 0 a 1 para que la sensibilidad sea estándar
    rms_norm = (rms - np.min(rms)) / (np.max(rms) - np.min(rms) + 1e-6)

    # Buscar el momento exacto donde se supera el umbral
    trigger_index = -1
    for i, nivel in enumerate(rms_norm):
        if nivel > sensibilidad:
            trigger_index = i
            break

    if trigger_index != -1:
        tiempo_inicio = librosa.frames_to_time(trigger_index, sr=sr, hop_length=512)
        print(f"\n [ANOMALÍA DETECTADA] en el segundo: {tiempo_inicio:.2f}")

        # --- CAPTURA DE 10 SEGUNDOS PARA LA IA ---
        inicio_samples = int(tiempo_inicio * sr)
        fin_samples = inicio_samples + (10 * sr)
        segmento_ia = y[inicio_samples:fin_samples]

        # --- VISUALIZACIÓN ---
        plt.figure(figsize=(10, 3))
        plt.plot(rms_norm, label='Energía detectada', color='blue')
        plt.axhline(y=sensibilidad, color='red', linestyle='--', label='Umbral de Alerta')
        plt.axvline(x=trigger_index, color='orange', label='Punto de Disparo')
        plt.title("Visualización del Gatillo RMS (Nivel de Energía)")
        plt.xlabel("Tramas de tiempo")
        plt.ylabel("Energía Normalizada")
        plt.legend()
        plt.show()

        # --- REPRODUCTOR DEL RECORTE ---
        print(f"▶️ ESCUCHANDO EL RECORTE DE 10s (Lo que recibirá YAMNet):")
        display(Audio(segmento_ia, rate=sr))

        return segmento_ia
    else:
        print("El audio ambiental no superó el umbral de sensibilidad.")
        return None

# --- 3. EJECUCIÓN DEL SISTEMA ---

# Nota: sensibilidad=0.3 es un punto medio.
# Si hay mucho ruido de fondo, súbelo a 0.5.
if 'filename' in locals():
    audio_detectado = pipeline_safevoice_completo(filename, sensibilidad=0.3)
else:
    print(" Primero debes subir un archivo.")

import io

def preprocesar_audio(audio_raw):
    # Normalización de pico: hace que el valor más alto sea 1.0 o -1.0
    if np.max(np.abs(audio_raw)) > 0:
        audio_norm = audio_raw / np.max(np.abs(audio_raw))
    else:
        audio_norm = audio_raw
    return audio_norm
def calcular_cercania(v1, v2):
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

import json


# Carga de patrones maestros - ASEGÚRATE QUE EL NOMBRE SEA EXACTO
with open('patrones_safevoice_26.json', 'r') as f:
    patrones_dict = json.load(f)

for filename in uploaded.keys():
    audio_raw, _ = librosa.load(io.BytesIO(uploaded[filename]), sr=16000, mono=True)
    audio_listo = preprocesar_audio(audio_raw)

    print(f"\n🎧 Analizando Detecciones Positivas: {filename}")
    print("-" * 75)
    print(f"{'Tiempo':<10} | {'Estado':<10} | {'Patrón Detectado':<25} | {'Score'}")
    print("-" * 75)

    segmento = 15600
    detecciones_encontradas = 0

    for i in range(0, len(audio_listo) - segmento, segmento):
        ventana = audio_listo[i : i + segmento].astype(np.float32)

        # Inferencia TFLite
        interpreter.resize_tensor_input(input_details[0]['index'], [len(ventana)])
        interpreter.allocate_tensors()
        interpreter.set_tensor(input_details[0]['index'], ventana)
        interpreter.invoke()

        embedding_segundo = interpreter.get_tensor(output_details[1]['index'])[0]

        # Comparación vs 26 Patrones
        mejor_puntaje = -1
        ganador = ""
        for nombre, vector in patrones_dict.items():
            puntaje = calcular_cercania(embedding_segundo, vector)
            if puntaje > mejor_puntaje:
                mejor_puntaje = puntaje
                ganador = nombre

        # FILTRO CRÍTICO: Solo mostramos si es mayor a 0
        if mejor_puntaje > -0.03:
            tiempo = i / 16000
            detecciones_encontradas += 1
            # Si el score es muy alto (ej. > 0.4), ponemos la sirena de alerta
            icono = "ALERTA" if mejor_puntaje > -0.021 else "-"
            print(f"{tiempo:>5.1f}s     | {icono:<10} | {ganador:<25} | {mejor_puntaje:.4f}")

    if detecciones_encontradas == 0:
        print("No se encontraron coincidencias positivas en este archivo.")

    print("-" * 75)

#UMBRAL

    if mejor_puntaje > -0.0209:
        tiempo = i / 16000
        detecciones_encontradas += 1
