"""add monitoring_active to users

Revision ID: 10922d31f2be
Revises: c8946725b0c5
Create Date: 2026-04-06 00:15:55.364464

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '10922d31f2be'
down_revision: Union[str, None] = 'c8946725b0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monitoring_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'monitoring_active')
    # ### end Alembic commands ###