"""agregar columna fcm_token a users

Revision ID: c8946725b0c5
Revises: 
Create Date: 2026-04-05 22:41:00.940068

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c8946725b0c5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###